App/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from App.models import *

blue = Blueprint('blog', __name__)


# 博客首页
@blue.route('/')
def user_index():
    contents = Content.query.all()
    classifications = Classification.query.all()
    return render_template('home/index.html', contents=contents, classifications=classifications)

# 首页搜索
@blue.route('/index/search/', methods=['GET', 'POST'])
def user_search():
    if request.method == 'POST':
        keywords = request.form.get('keyboard')
        # print(keywords)
        if Content.query.filter(Content.keyword==keywords).count():
            contents = Content.query.filter(Content.keyword==keywords)
            classifications = Classification.query.all()
            return render_template('home/index.html', contents=contents, classifications=classifications)
        elif Classification.query.filter(Classification.keyword == keywords).count():
            classifications = Classification.query.filter(Classification.keyword == keywords)
            # print(classifications)
            contents = []
            for classification in classifications:
                content = Classification.query.get(classification.id).contents
                contents.extend(content)
            classifications = Classification.query.all()
            return render_template('home/index.html', contents=contents, classifications=classifications)
        else:
            classifications = Classification.query.all()
            contents = Content.query.all()
            return render_template('home/index.html', contents=contents, classifications=classifications)
    else:
        classifications = Classification.query.all()
        contents = Content.query.all()
        return render_template('home/index.html', contents=contents, classifications=classifications)


# 首页分类搜索栏
@blue.route('/index/fenlei/<int:classificationid>')
def user_fenlei1(classificationid):
    classifications = Classification.query.all()
    contents = Classification.query.get(classificationid).contents
    return render_template('home/index.html', contents=contents, classifications=classifications)

# 关于我
@blue.route('/about/')
def user_about():
    classifications = Classification.query.all()
    return render_template('home/about.html', classifications=classifications)

# 留言
@blue.route('/gbook/')
def user_gbook():
    classifications = Classification.query.all()
    return render_template('home/gbook.html', classifications=classifications)

# 内容页
@blue.route('/info/')
def user_info():
    classifications = Classification.query.all()
    return render_template('home/info.html', classifications=classifications)

# 内容页2
@blue.route('/infopic/')
def user_infopic():
    classifications = Classification.query.all()
    return render_template('home/infopic.html', classifications=classifications)

# 我的日记
@blue.route('/list/')
def user_list():
    contents = Content.query.all()
    classifications = Classification.query.all()
    return render_template('home/list.html', contents=contents, classifications=classifications)

# 日记分类搜索
@blue.route('/list/fenlei/<int:classificationid>')
def user_fenlei2(classificationid):
    classifications = Classification.query.all()
    contents = Classification.query.get(classificationid).contents
    return render_template('home/list.html', contents=contents, classifications=classifications)

# 留言分类搜索
@blue.route('/index/fenlei/<int:classificationid>')
def user_fenlei3(classificationid):
    classifications = Classification.query.all()
    contents = Classification.query.get(classificationid).contents
    return render_template('home/index.html', contents=contents, classifications=classifications)

# 关于我分类搜索
@blue.route('/index/fenlei/<int:classificationid>')
def user_fenlei4(classificationid):
    classifications = Classification.query.all()
    contents = Classification.query.get(classificationid).contents
    return render_template('home/index.html', contents=contents, classifications=classifications)

# 内容页1分类搜索
@blue.route('/index/fenlei/<int:classificationid>')
def user_fenlei5(classificationid):
    classifications = Classification.query.all()
    contents = Classification.query.get(classificationid).contents
    return render_template('home/index.html', contents=contents, classifications=classifications)

# 内容页2分类搜索
@blue.route('/index/fenlei/<int:classificationid>')
def user_fenlei6(classificationid):
    classifications = Classification.query.all()
    contents = Classification.query.get(classificationid).contents
    return render_template('home/index.html', contents=contents, classifications=classifications)


# 我的相册
@blue.route('/share/')
def user_share():
    # contents = Content.query.all()
    # classifications = Classification.query.all()
    res = redirect(url_for('blog.user_share_page', page=1))
    # return render_template('admin/article.html', contents=contents, username=username)
    return res

# 我的相册分页
@blue.route('/share/<int:page>', methods=['GET', 'POST'])
def user_share_page(page):
    if not page:
        page = 1
    # page = int(request.args.get('page', 1))  # 页码，1 是设置默认打开是第一页
    # per_page = int(request.args.get('per_page', 3))  # 每页显示的个数
    # contents = Content.query.offset((page - 1) * per_page).limit(per_page)
    c = Content.query.paginate(page=page, per_page=8, error_out=False)
    # contents = c.items
    # contents = Content.query.all()
    # classifications = Classification.query.all()
    return render_template('home/share.html', contents=c)

# 后台登录
@blue.route('/admin/login/', methods=['GET', 'POST'])
def admin_login():
    if request.method == 'POST':
        # 接收客户端提交的参数
        username = request.form.get('username')
        userword = request.form.get('userpwd')
        # 验证登录是否能成功
        if username == '刘先生' and userword == '123456':
            res = redirect(url_for('blog.admin_index'))  # 重定向到index.html
            # 设置session
            session["username"] = username
            return res
        return 'login failed'
    return render_template('admin/login.html')

# 后台退出登录
@blue.route('/admin/deletelogin/')
def delete_login():
    res = redirect(url_for('blog.admin_login'))
    # 删除session
    session.pop('username')
    return res

# 后台首页
@blue.route('/admin/index/')
def admin_index():
    # session获取
    count = len(Content.query.all())
    username = session.get('username', '')
    if username == '':
        res = redirect(url_for('blog.admin_login'))
        return res
    return render_template('admin/index.html', username=username, count=count)

# 后台文章
@blue.route('/admin/article/', methods=['GET', 'POST'])
def admin_article():
    # contents = Content.query.all()
    username = session.get('username', '')
    if username == '':
        res1 = redirect(url_for('blog.admin_login'))
        return res1
    # classifications = Classification.query.all()
    res = redirect(url_for('blog.admin_article_page', page=1))
    # return render_template('admin/article.html', contents=contents, username=username)
    return res

# 后台文章分页
@blue.route('/admin/article/<int:page>', methods=['GET', 'POST'])
def admin_article_page(page):
    if not page:
        page = 1
    # page = int(request.args.get('page', 1))  # 页码，1 是设置默认打开是第一页
    # per_page = int(request.args.get('per_page', 3))  # 每页显示的个数
    # contents = Content.query.offset((page - 1) * per_page).limit(per_page)
    c = Content.query.paginate(page=page, per_page=6, error_out=False)
    # contents = c.items
    # contents = Content.query.all()
    username = session.get('username', '')
    # classifications = Classification.query.all()
    return render_template('admin/article.html', contents=c, username=username)

# 添加文章
@blue.route('/admin/add_article/', methods=['GET', 'POST'])
def admin_add_article():
    # contents = Content.query.all()
    classifications = Classification.query.all()
    username = session.get('username', '')
    if username == '':
        res = redirect(url_for('blog.admin_login'))
        return res
    if request.method == 'POST' and request.form.get('title') and request.form.get('content'):
        # 接收客户端提交的参数
        c = Content()
        c.title = request.form.get('title')
        c.text = request.form.get('content')
        c.keyword = request.form.get('keywords')
        c.describe = request.form.get('describe')
        c.classification = request.form.get('category')
        c.label = request.form.get('tags')
        c.img = request.form.get('titlepic')
        c.data = request.form.get('time')
        db.session.add(c)
        db.session.commit()
        res = redirect(url_for('blog.admin_add_article'))
        return res
    return render_template('admin/add-article.html', classifications=classifications, username=username)


# 后台栏目
@blue.route('/admin/category/', methods=['GET', 'POST'])
def admin_category():
    # contents = Content.query.all()
    username = session.get('username', '')
    if username == '':
        res = redirect(url_for('blog.admin_login'))
        return res
    classifications = Classification.query.all()
    if request.method == 'POST':
        # 接收客户端提交的参数
        c = Classification()
        c.name = request.form.get('name')
        c.alias = request.form.get('alias')
        c.keyword = request.form.get('keywords')
        c.describe = request.form.get('describe')
        c.parentnode = request.form.get('fid')  # 父节点
        db.session.add(c)
        db.session.commit()
        res = redirect(url_for('blog.admin_category'))
        return res
    return render_template('admin/category.html', classifications=classifications, username=username)

# 更新文章
@blue.route('/admin/update-article/<int:contentid>', methods=['GET', 'POST'])

App/templates/home/about.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_未来树个人博客 - 一个站在莽苍山之路的马上催个人博客网站</title>
<meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青" />
<meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="../../static/home/css/base.css" rel="stylesheet">
<link href="../../static/home/css/index.css" rel="stylesheet">
<link href="../../static/home/css/m.css" rel="stylesheet">
<script src="../../static/home/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="../../static/home/js/hc-sticky.js"></script>
<script type="text/javascript" src="../../static/home/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">未来树个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{{ url_for('blog.user_index') }}">网站首页</a></li>
      <li><a href="{{ url_for('blog.user_share') }}">我的相册</a></li>
      <li><a href="{{ url_for('blog.user_list') }}">我的日记</a></li>
      <li><a href="{{ url_for('blog.user_about') }}">关于我</a></li>
      <li><a href="{{ url_for('blog.user_gbook') }}">留言</a></li>
      <li><a href="{{ url_for('blog.user_info') }}">内容页</a></li>
      <li><a href="{{ url_for('blog.user_infopic') }}">内容页</a></li>
    </ul>
</nav>
</header>
<article>
  <aside class="l_box">
    <div class="about_me">
      <h2>关于我</h2>
      <ul>
        <i><img src="../../static/home/images/4.jpg"></i>
        <p><b>未来树</b>，一个90后绝无神站长！20年入行。一直潜心研究绝无神技术，一边工作一边积累经验，分享一些个人博客模板，以及杀神之路等心得。</p>
      </ul>
    </div>
    <div class="wdxc">
      <h2>我的相册</h2>
      <ul>
        <li><a href="/"><img src="../../static/home/images/7.jpg"></a></li>
        <li><a href="/"><img src="../../static/home/images/8.jpg"></a></li>
        <li><a href="/"><img src="../../static/home/images/9.jpg"></a></li>
        <li><a href="/"><img src="../../static/home/images/10.jpg"></a></li>
        <li><a href="/"><img src="../../static/home/images/11.jpg"></a></li>
        <li><a href="/"><img src="../../static/home/images/12.jpg"></a></li>
      </ul>
    </div>
    <div class="search">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei">
      <h2>文章分类</h2>
      <ul>
        {% for classification in classifications %}
                <li><a href="{{ url_for('blog.user_fenlei3', classificationid=classification.id) }}">{{ classification.name }}（{{ classification.contents.count() }}）</a></li>
        {% endfor %}
      </ul>
    </div>
   
    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="../../static/home/images/wx.jpg">
      </ul>
    </div>
  </aside>
  <main class="r_box">
     <div class="about">
      <p>徐根凯，，男，一个90后，一个从建筑行业到互联网编程专业的转行的小伙子，从现在开始踏上编程的路上学习。 。<br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
    <img src="../../static/home/images/1.jpg">        近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
            现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br />
            <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，280998807(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群 。我的个人微信号 yangqq_1987）</p>
          <br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
    <img src="../../static/home/images/1.jpg">        近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
            现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br />
            <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，280998807(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群 。我的个人微信号 yangqq_1987）</p>
          <br />
          <h2>About my blog</h2>
          &nbsp;
          <p>域 名：www.yangqq.com 创建于2011年01月12日&nbsp;</p>
          <br />
          <p>服务器：阿里云服务器&nbsp;&nbsp;<a href="https://promotion.aliyun.com/ntms/act/ambassador/sharetouser.html?userCode=8smrzoqa&amp;productCode=vm" target="_blank"><span style="color:#FF0000;"><strong>前往阿里云官网购买&gt;&gt;</strong></span></a></p>
          <br />
          <p>备案号：蜀ICP备11002373号-1</p>
          <br />
          <p>程 序：PHP 帝国CMS7.5</p>
  
     </div>
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">未来树个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>

App/templates/home/index.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_未来树个人博客 - 一个站在莽苍山之路的马上催个人博客网站</title>
<meta name="keywords" content="个人博客,未来树个人博客,个人博客模板,未来树" />
<meta name="description" content="未来树个人博客，是一个站在莽苍山之路的马上催个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="../../static/home/css/base.css" rel="stylesheet">
<link href="../../static/home/css/index.css" rel="stylesheet">
<link href="../../static/home/css/m.css" rel="stylesheet">
<script src="../../static/home/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="../../static/home/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="../../static/home/js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">未来树个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{{ url_for('blog.user_index') }}">网站首页</a></li>
      <li><a href="{{ url_for('blog.user_share') }}">我的相册</a></li>
      <li><a href="{{ url_for('blog.user_list') }}">我的日记</a></li>
      <li><a href="{{ url_for('blog.user_about') }}">关于我</a></li>
      <li><a href="{{ url_for('blog.user_gbook') }}">留言</a></li>
      <li><a href="{{ url_for('blog.user_info') }}">内容页</a></li>
      <li><a href="{{ url_for('blog.user_infopic') }}">内容页</a></li>
    </ul>
</nav>
</header>
<article>
  <aside class="l_box">
      <div class="about_me">
        <h2>关于我</h2>
        <ul>
          <i><img src="../../static/home/images/4.jpg"></i>
          <p><b>未来树</b>，一个90后绝无神站长！20年入行。一直潜心研究绝无神技术，一边工作一边积累经验，分享一些个人博客模板，以及杀神之路等心得。</p>
        </ul>
      </div>
      <div class="wdxc">
        <h2>我的相册</h2>
        <ul>
          <li><a href="/"><img src="../../static/home/images/7.jpg"></a></li>
          <li><a href="/"><img src="../../static/home/images/8.jpg"></a></li>
          <li><a href="/"><img src="../../static/home/images/9.jpg"></a></li>
          <li><a href="/"><img src="../../static/home/images/10.jpg"></a></li>
          <li><a href="/"><img src="../../static/home/images/11.jpg"></a></li>
          <li><a href="/"><img src="../../static/home/images/12.jpg"></a></li>
        </ul>
      </div>
      <div class="search">
        <form action="{{ url_for('blog.user_search')}}" method="post" name="searchform" id="searchform">
          <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>
      <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
            {% for classification in classifications %}
                <li><a href="{{ url_for('blog.user_fenlei1', classificationid=classification.id) }}">{{ classification.name }}（{{ classification.contents.count() }}）</a></li>
            {% endfor %}
        </ul>
      </div>
      <div class="tuijian">
        <h2>站长推荐</h2>
        <ul>
          <li><a href="http://www.haha56.net/xiaohua/xiaosi/">超级短笑话,条条精彩，笑死人不偿命</a></li>
          <li><a href="https://www.gushiwen.org/index.aspx">恰同学少年，风华正茂，书生意气，挥斥方遒。</a></li>
          <li><a href="https://mbd.baidu.com/newspage/data/landingsuper?context=%7B%22nid%22%3A%22news_9566678311840836578%22%7D&n_type=0&p_from=1">国际观察｜G20大阪峰会看点扫描</a></li>
          <li><a href="https://m.xinli001.com/activity/248">九型人格测试：测你是哪一型人格</a></li>
          <li><a href="http://sports.ifeng.com/c/7nouT4bPx1z">中国女足完败意大利无缘世界杯八强！</a></li>
          <li><a href="https://baijiahao.baidu.com/s?id=1637390069671018236&wfr=spider&for=pc">生活垃圾分类制度将入法</a></li>
          <li><a href="https://baijiahao.baidu.com/s?id=1637379181212400252&wfr=spider&for=pc">中国域名根服务器来了 网络管理不受制于人</a></li>
          <li><a href="https://mbd.baidu.com/newspage/data/landingsuper?context=%7B%22nid%22%3A%22news_8979904114669408467%22%7D&n_type=0&p_from=1">“这是一个奖励创作者的时代！”</a></li>
        </ul>
      </div>
      <div class="links">
        <h2>友情链接</h2>
        <ul>
          <a href="http://www.yangqq.com">未来树个人博客</a> <a href="http://www.yangqq.com">未来树博客</a>
        </ul>
      </div>
      <div class="guanzhu">
        <h2>关注我 么么哒</h2>
        <ul>
          <img src="../../static/home/images/wx.jpg">
        </ul>
      </div>
  </aside>
  <main class="r_box">
      {% for content in contents %}
          <li><i><a href="/"><img src="{{ content.img }}"></a></i>
              <h3><a href="/">{{ content.title }}</a></h3>
              <p>{{ content.text | safe }}</p>
              <p style="font-size: 10px">{{ content.data }}</p>
          </li>
      {% endfor %}
    
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">未来树个人博客</a> <a href="/">赣BCP备11002571号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>

App/templates/home/share.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_未来树个人博客 - 一个站在莽苍山之路的马上催个人博客网站</title>
    <style>
        .disabled {
            pointer-events: none;
            cursor: default;
            opacity: 0.6;
        }
    </style>
<meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青" />
<meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="../../static/home/css/base.css" rel="stylesheet">
<link href="../../static/home/css/index.css" rel="stylesheet">
<link href="../../static/home/css/m.css" rel="stylesheet">
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
<script src="../../static/home/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="../../static/home/js/comm.js"></script>
<script src="../../static/home/js/scrollReveal.js"></script>
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">未来树个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{{ url_for('blog.user_index') }}">网站首页</a></li>
      <li><a href="{{ url_for('blog.user_share') }}">我的相册</a></li>
      <li><a href="{{ url_for('blog.user_list') }}">我的日记</a></li>
      <li><a href="{{ url_for('blog.user_about') }}">关于我</a></li>
      <li><a href="{{ url_for('blog.user_gbook') }}">留言</a></li>
      <li><a href="{{ url_for('blog.user_info') }}">内容页</a></li>
      <li><a href="{{ url_for('blog.user_infopic') }}">内容页</a></li>
    </ul>
</nav>
</header>
<article>
  <div class="picbox">

        {% for content in contents.items %}
            <ul>
              <li style="width: 240px;height: 298px;overflow: hidden" data-scroll-reveal="enter bottom over 1s" ><a href="/"><i><img src="{{ content.img }}"></i>
                  <div class="picinfo">
                  <h3>{{ content.title }}</h3>
                  <span>{{ content.text | safe }}</span></div>
              </a></li>
            </ul>
        {% endfor %}



  </div>
    <div class="pagelist"><a class="allpage"
                {% if not contents.has_prev %} class="allpage"{% endif %}
             href="{% if contents.has_prev %}{{ url_for('blog.user_share_page',page = contents.page - 1) }}
            {% else %}#{% endif %}">上一页
            </a>
            {% for p in contents.iter_pages() %}
                {% if p %}
                    {% if p == contents.page %}

                        <a class="curPage" href="{{ url_for('blog.user_share_page', page = p) }}">{{ p }}</a>

                    {% else %}

                        <a href="{{ url_for('blog.user_share_page', page = p) }}">{{ p }}</a>

                    {% endif %}
                {% else %}

                    <a href="#">&hellip;</a>

                {% endif %}
            {% endfor %}
       <a class="allpage"{% if not contents.has_next %} class="disabled"{% endif %}
             href="{% if contents.has_next %}{{ url_for('blog.user_share_page',page = contents.page + 1) }}{% else %}#{% endif %}">下一页</a>

    </div>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">未来树个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
<script>
	if (!(/msie [6|7|8|9]/i.test(navigator.userAgent))){
		(function(){
			window.scrollReveal = new scrollReveal({reset: true});
		})();
	};
</script>
</body>
</html>